---
application:
  name: "techjobs-scraper"
  project: "techjobs"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "techjobs"
  version: "11"
routers:
- name: "main-techjobs-scraper"
  routes:
  - application_name: "techjobs-scraper"
    paths:
    - "/*"
