# This is a basic workflow to help you get started with Actions

name: Scrape

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron:  '15 8,20 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  stackoverflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: npm install
      - name: get jobs from stackoverflow
        run: node stackoverflow-parser.js --trace-warnings
        env:
          TECHJOBS_API: https://techjobs.sg
  techinasia:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: npm install      
      - name: get jobs from techinasia
        run: node techinasia-scraper.js --trace-warnings
        env:
          TECHJOBS_API: https://techjobs.sg
  adzuna:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: npm install      
      - name: get jobs from adzuna
        run: node adzuna-parser.js --trace-warnings
        env:
          TECHJOBS_API: https://techjobs.sg
  mycareersfuture:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: npm install      
      - name: get jobs from mycareersfuture
        run: node mcf-parser.js --trace-warnings
        env:
          TECHJOBS_API: https://techjobs.sg
  sync-company-data:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: npm install      
      - name: sync company data
        run: node sync-company-data.js --trace-warnings
        env:
          BASEROW_API_KEY: ${{ secrets.BASEROW_API_KEY }}
          LI_AT_COOKIE: ${{ secrets.LI_AT_COOKIE }}
          TECHJOBS_API: https://techjobs.sg
